### ISSUE TITLE
Textfield cannot be edited when the color picker is used within a Bootstrap modal dialog

### ISSUE THREAD

**Issue by colinvella** [bgrins/spectrum#161]
When the spectrum color picker is used within a Bootstrap modal dialog, the text field (enabled via the showInput option) is visible but cannot be edited. This issue seems to be related to a similar issue that occurs when using jQuery dialog.

**Comment by broken-e** [comment]
I had this problem as well with the JQuery UI dialog as well. I tried the workaround in the jsfiddle and it did help, but the color picker was showing underneath the dialog border. I realized that the issue is because the dialog was modal, disallowing interaction with elements not within it, and the spectrum element is appended to the body. I discovered that you can whitelist elements for JQueryUI dialog by extending the widget in the widget factory. The code that did it is: 
```
$.widget("custom.dialog", $.ui.dialog, {
    _allowInteraction: function (event) {
        return !!$(event.target).is(".sp-input") || this._super(event);
    }
});
```

**Comment by subtleBreeze** [comment]
I had the same issue. 
Removing 'tabindex=-1' from the modal attributes worked for me.

**Comment by computerUser9** [comment]
There's still a problem here. The colorpicker works ok on a modal, but it leaves remnant input boxes on the main screen when the modal is dismissed. I'm removing .sp-containers with jquery on form submission, but it should clean up after itself better than it does.

**Comment by HansPeterOrding** [comment]
I had a similar problem with a tinymce in a modal dialog (the insert link popup did not focus). The workaround for this problem (slightly modified) works here too:

$(document).on('focusin', function(e) {
            if ($(e.target).closest(".sp-container").length) {
                e.stopImmediatePropagation();
            }
        });

It seems that the bootstrap modal is hooked in event propagation. The snippet above prevents bootstrap from special propagation behaviours.
