### ISSUE TITLE
Dragger is not positioning right on flat:true with initial color

### ISSUE THREAD

**Issue by venfrancis** [bgrins/spectrum#216]
Hi we're using this great plugin for a project. We're encountering error when we try to put the flat:true with a initial color. The dragger's value is just set to 

``` html
<div class="sp-dragger" style="display: block; top: 110.2px; left: -5px;"></div>
```

. We're calling it through a loop while changing the target ID and then call the spectrum(). Without flat:true, all is working fine. We also checked the css for conflicts but nothing is causing the issue from css side. I guess there's really an issue with flat:true option because the values above is set for **all of the colorpicker instances** 

Kindly advise :)

Best,
Ven

**Comment by medBouzid** [comment]
@bgrins I am using the latest version 1.8.0 and the issue is still the same, I have a flat:true spectrum inside a hidden div, when I click a button, the div show up and spectrum as well, the sp-dragger isn't positioned, your previous solution `$("element").spectrum("reflow")` works, but maybe you have planed to solve it natively, I admit that it was painful to solve it without reading this, thanks!
