### ISSUE TITLE
Picker accuracy is limited by size of gradients

### ISSUE THREAD

**Issue by liitii** [bgrins/spectrum#419]
There are 255 steps for each channel in 32bit colorspace but the colour square, and hue and alpha sliders are only about 140px wide, less if `allowEmpty`.

Could you enlarge these to 255px to allow full range of selection? Perhaps via a `large` config option if you don't want it to be the default? It would make a difference when trying to select faint colours, and ensure that specific colours (like those in trademarks) aren't corrupted.

**Comment by 75th** [comment]
The color picker is actually using HSL color, not RGB. Photoshop's HSL picker only allows 100 steps of granularity in saturation and lightness, so it's only hue that is losing resolution compared to Photoshop. Unfortunately, you'd need 361 pixels of height to represent hue at full-res, and that's a bit large.

Alpha also doesn't really need more than about 100 steps, since almost everyone <sup>[citation needed]</sup> uses a one- or two-decimal float between 0 and 1 in `rgba()`.

Finally, if you're eyeballing a color using the color picker instead of just typing in a hex code you already know, you don't really need 16.7 million options; the 2.7 million you've already got probably ought to do.

**Comment by liitii** [comment]
That's swell, but the web uses rgb(a), probably because almost everyone's screens do. I don't know what version of PS you're using but mine has 256 gradations in each dimension.

Colour information should not be lost just because someone uses a particular interface to control it. Just because most cases do not need that level of precision, it doesn't mean you should be forced to use two interfaces to control the same datum, and have cumbersome logic to ensure one doesn't break the other.

It's not about 'eyeballing' colours, it's about being able to change colours when you want, and have others set precisely, when required. I take it you don't have much contact with fastidious designers?

Also, I already put in an (accepted) fix that preserves 256 levels of alpha.

**Comment by 75th** [comment]
> That's swell, but the web uses rgb(a), probably because almost everyone's screens do.

Of course it does, I'm just saying that the spectrum you see with this color picker AND Photoshop's default one reflects HSL space. It has a slider for Hue, and one axis of the color square is Saturation and the other axis is Lightness.

>  I don't know what version of PS you're using but mine has 256 gradations in each dimension.

The color square is certainly more than 256px wide and tall, but if you drag the cursor around the square and watch the numbers change, Saturation and Lightness only adjust in increments of 1%. And if you watch the RGB colors change, in at least some places in the spectrum there are *multiple* HSL values corresponding to a single RGB color.

> Colour information should not be lost just because someone uses a particular interface to control it.

Yes, it should. The visual color picker is there to eyeball a good color when you don't have an exact hex code to match. No one in history has tried to match a particular, pre-known RGB color by sliding to a certain hue and dragging that dot around the square — or if they did, it was for fun and not for productivity.

> it doesn't mean you should be forced to use two interfaces to control the same datum

If I'm trying to input a particular one of the 16.7 million possible RGB colors, then I certainly hope something would force me to type it in instead of hunting for it with a color picker.

> It's not about 'eyeballing' colours

Yes, that is precisely the purpose of a visual color picker. If you're not eyeballing the color that means you already know it, and if you already know it, anyone not literally insane will type it in.

> it's about being able to change
> colours when you want, and have others set precisely, when required.

Which you can, *by typing them in.* Sincerely using the visual picker when it's "required" to set a specific color is a good way to inflate billable hours and not much else that I can think of.

> I take it you don't have much contact with fastidious designers?

This almost makes me think you're just trolling. But of course I couldn't resist feeding you anyway.

> Also, I already put in an (accepted) fix that preserves 256 levels of alpha.

Congratulations on allowing a precision of opacity that no designer has used in the history of ever.

I apologize to @bgrins for turning his issue queue into a "*SOMEONE IS **WRONG** ON THE INTERNET*" zone. I promise I won't do it again.

**Comment by liitii** [comment]
Never mind, I had `showInput: true` but the input in the colour picker popup was being incorrectly set as `readonly` by something else, so I thought that spectrum intentionally blocked editing.

@75th Yet, Photoshop preserves the accuracy of colours as entered.

>> It's not about 'eyeballing' colours
>
> Yes, that is precisely the purpose of a visual color picker.

*This issue* isn't; context.

> Congratulations on allowing a precision of opacity that no designer has used in the history of ever.

Maybe, but the change fixed some pretty ugly results where some server-side image processing code I had to use was sensitive to alpha values. (And no, typing the value manually into the input wouldn't have worked, because rounding to 2 decimals is enforced by the parser.)

Don't think you can know everyone's use cases for such a generic tool, you end up looking like one.
