### ISSUE TITLE
Gradient Support Suggestion

### ISSUE THREAD

**Issue by recepkutuk** [bgrins/spectrum#480]
I am a big fan of spectrum and I believe a gradient support addition would be a great addition to take it to a whole new level.

It is hard to tell but what I have in mind is a gradient tool similar to Photoshop. I even made a sketch of it but I have no idea if this is practical or we need a whole different solution.

![suggestion](https://cloud.githubusercontent.com/assets/994097/26447210/1d5088a8-4150-11e7-94d0-111cb9f710a7.jpg)

**Comment by recepkutuk** [comment]
Here is a better idea: https://blog.framer.com/introducing-framer-gradients-c5975a4129ec

**Comment by bgrins** [comment]
> Here is a better idea: https://blog.framer.com/introducing-framer-gradients-c5975a4129ec

That looks pretty nice!  I'm going to close this issue since I think it would be best handled in a different package that wraps spectrum rather than the colorpicker itself, but I'd be happy to see and link to a project that did so

**Comment by no1youknowz** [comment]
Big fan here too.

I was hoping that gradient would be added, sad to see the issue closed.

So, I forked it myself and added them in.  Wasn't too difficult.

Solid Color:

![Solid](http://i.imgur.com/ErWfNrT.png)

Gradient:

![Gradient](http://i.imgur.com/bl1Ku8q.png)

**Comment by recepkutuk** [comment]
OMG THAT'S GREAT!!

So sorry if I am asking a newbie question (because I'm one) is there a way I can obtain this?

**Comment by no1youknowz** [comment]
I'm still working on it, but soon it'll be at a point where I'm satisfied with it.

I'll fork the repo and then make an example on codepen.

Of course, you'll need to keep in mind.  Absolutely no warranty with it.  I'm able to support it for myself, because I find developing in javascript really easy :1st_place_medal: 

If @bgrins at a later date, wants to fold in the changes and optimise the code.  That would be better for you!

**Comment by recepkutuk** [comment]
I'm really looking forward to this, thank you very very much! 🙂

**Comment by paulm17** [comment]
Seems hindsight is everything.  As I try to package it up for a demo on codepen, I'm finding I'm not able to get it to work as easily outside of my platform.  Seems I have forked it too much and relies on internal components.

To be fair, I've broken some "laws" of spectrum by doing this fork.

I agree with @bgrins that probably the best way forward is a separate plugin that relies on spectrum.  Unfortunately, I didn't write my work this way.

Sadly I have run out of time and I need to be working on other things.  It's really not that difficult to fork, this took me 24 hours to do, from start to finish.

If I ever return to this, then I'll see what I can do.  But otherwise, I think a gradient tool will be "pending".
